package app

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/Zen1th53/marshal/internal/adapter"
	"github.com/Zen1th53/marshal/internal/adapter/codex"
	"github.com/Zen1th53/marshal/internal/constitution"
	"github.com/Zen1th53/marshal/internal/evidence"
	"github.com/Zen1th53/marshal/internal/execution"
	"github.com/Zen1th53/marshal/internal/goalintake"
	"github.com/Zen1th53/marshal/internal/model"
	"github.com/Zen1th53/marshal/internal/plan"
	"github.com/Zen1th53/marshal/internal/verification"
)

type fakeGovernedCodexAdapter struct {
	runs          int
	probes        int
	lastReq       adapter.Request
	allowedModels map[string]bool
}

func newFakeCodexAdapter() *fakeGovernedCodexAdapter {
	return &fakeGovernedCodexAdapter{
		allowedModels: map[string]bool{
			"gpt-5.6-terra": true,
			"gpt-6-astra":   true,
		},
	}
}

func (f *fakeGovernedCodexAdapter) Probe(context.Context) (adapter.Probe, error) {
	f.probes++
	return adapter.Probe{
		Name:      "codex",
		Available: true,
		Version:   "codex-cli 0.154.0",
		Capabilities: map[string]string{
			"run": "native", "sandbox": "native", "resume": "unsupported",
		},
	}, nil
}

func (f *fakeGovernedCodexAdapter) Capabilities() map[string]string {
	return map[string]string{
		"run": "native", "sandbox": "native", "resume": "unsupported",
	}
}

func (f *fakeGovernedCodexAdapter) ValidateModel(_ context.Context, modelName string) error {
	if f.allowedModels[modelName] {
		return nil
	}
	return fmt.Errorf("%w: model %q not eligible", model.ErrInvalid, modelName)
}

func (f *fakeGovernedCodexAdapter) Run(ctx context.Context, req adapter.Request) (adapter.Result, error) {
	f.runs++
	f.lastReq = req

	// Mutate worktree so commitTaskChanges produces a commit
	testFile := filepath.Join(req.Worktree, "codex_output.txt")
	if err := os.WriteFile(testFile, []byte("generated by codex"), 0o644); err != nil {
		return adapter.Result{}, err
	}

	return adapter.Result{
		Adapter:        "codex",
		AdapterVersion: "0.154.0",
		Model:          req.Model,
		SessionID:      "thread_codex_governed_123",
		Status:         adapter.StatusSuccess,
		ExitCode:       0,
		Stdout:         []byte("{\"type\":\"thread.started\",\"thread_id\":\"thread_codex_governed_123\"}\n"),
	}, nil
}

func (f *fakeGovernedCodexAdapter) Status(context.Context, string) (adapter.Status, error) {
	return adapter.StatusSuccess, nil
}

func (f *fakeGovernedCodexAdapter) Resume(context.Context, string, adapter.Request) (adapter.Result, error) {
	return adapter.Result{}, fmt.Errorf("%w: resume blocked", model.ErrUnavailable)
}

func (f *fakeGovernedCodexAdapter) Shutdown(context.Context, string) error {
	return nil
}

func (f *fakeGovernedCodexAdapter) CollectEvidence(result adapter.Result) map[string]any {
	return map[string]any{
		"session_id": result.SessionID,
		"model":      result.Model,
	}
}

func TestCodexModelValidationBeforeClaim(t *testing.T) {
	ctx := context.Background()
	repo := runtimeRepo(t)
	if _, err := Bootstrap(ctx, repo.Path()); err != nil {
		t.Fatal(err)
	}

	fake := newFakeCodexAdapter()
	runtime, err := OpenWithOptions(ctx, repo.Path(), Options{
		Adapters: map[string]adapter.Adapter{"codex": fake},
	})
	if err != nil {
		t.Fatal(err)
	}
	defer runtime.Close()

	agent, err := runtime.RegisterAgent(ctx, RegisterAgentRequest{Name: "dev-codex", Role: model.RoleDeveloper, ModelProvider: "codex"})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := runtime.ImportTasks(ctx, []model.Task{
		{ID: "TASK-CODEX-VALIDATION", Title: "test model validation", Status: model.TaskReady, Risk: model.R1},
	}); err != nil {
		t.Fatal(err)
	}

	// 1. Unknown model must fail closed before claim
	_, err = runtime.Run(ctx, RunRequest{
		TaskID:           "TASK-CODEX-VALIDATION",
		AgentID:          agent.ID,
		Adapter:          "codex",
		Model:            "gpt-fake-nonexistent",
		ExpectedRevision: 0,
	})
	if err == nil || !errors.Is(err, model.ErrInvalid) {
		t.Fatalf("expected ErrInvalid for unknown model, got %v", err)
	}

	// Ensure no lease or session was created
	sessCount, err := runtime.store.Count(ctx, "sessions")
	if err != nil || sessCount != 0 {
		t.Fatalf("sessions count = %d, want 0 after rejected model validation", sessCount)
	}
	leaseCount, err := runtime.store.Count(ctx, "leases")
	if err != nil || leaseCount != 0 {
		t.Fatalf("lease count = %d, err = %v, want 0 after rejected model validation", leaseCount, err)
	}
	if fake.runs != 0 {
		t.Fatalf("fake adapter was run %d times, want 0", fake.runs)
	}

	// Adapter/provider binding is checked before the lease or provider launch;
	// a Claude (or arbitrary) principal cannot borrow Codex execution simply by
	// naming adapter="codex" through a local caller.
	wrongProvider, err := runtime.RegisterAgent(ctx, RegisterAgentRequest{Name: "dev-claude", Role: model.RoleDeveloper, ModelProvider: "claude"})
	if err != nil {
		t.Fatal(err)
	}
	_, err = runtime.Run(ctx, RunRequest{
		TaskID: "TASK-CODEX-VALIDATION", AgentID: wrongProvider.ID, Adapter: "codex", Model: "gpt-5.6-terra", ExpectedRevision: 0,
	})
	if !errors.Is(err, model.ErrInvalid) {
		t.Fatalf("wrong provider must be refused before claim: %v", err)
	}
	sessCount, err = runtime.store.Count(ctx, "sessions")
	if err != nil || sessCount != 0 || fake.runs != 0 {
		t.Fatalf("wrong-provider attempt must not create a session or launch Codex: sessions=%d runs=%d err=%v", sessCount, fake.runs, err)
	}

	// 2. Dangerous bypass flag in model name must fail closed with ErrPolicyDenied
	agent2, err := runtime.RegisterAgent(ctx, RegisterAgentRequest{Name: "dev-codex-2", Role: model.RoleDeveloper, ModelProvider: "codex"})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := runtime.ImportTasks(ctx, []model.Task{
		{ID: "TASK-CODEX-DANGEROUS", Title: "test dangerous flag", Status: model.TaskReady, Risk: model.R1},
	}); err != nil {
		t.Fatal(err)
	}
	_, err = runtime.Run(ctx, RunRequest{
		TaskID:           "TASK-CODEX-DANGEROUS",
		AgentID:          agent2.ID,
		Adapter:          "codex",
		Model:            "--dangerously-bypass-approvals-and-sandbox",
		ExpectedRevision: 0,
	})
	if err == nil || !errors.Is(err, model.ErrPolicyDenied) {
		t.Fatalf("expected ErrPolicyDenied for dangerous flag, got %v", err)
	}
}

func TestProcess05CodexAgentRequiresEligibleUnambiguousCodexPrincipal(t *testing.T) {
	ctx := context.Background()
	repo := runtimeRepo(t)
	if _, err := Bootstrap(ctx, repo.Path()); err != nil {
		t.Fatal(err)
	}
	runtime, err := Open(ctx, repo.Path())
	if err != nil {
		t.Fatal(err)
	}
	defer runtime.Close()
	claude, err := runtime.RegisterAgent(ctx, RegisterAgentRequest{Name: "claude developer", Role: model.RoleDeveloper, ModelProvider: "claude"})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := runtime.process05CodexAgent(ctx, execution.TaskExecution{TaskID: "task", AssignedAgent: claude.ID}); !errors.Is(err, model.ErrUnavailable) {
		t.Fatalf("non-Codex assigned agent must be refused: %v", err)
	}
	first, err := runtime.RegisterAgent(ctx, RegisterAgentRequest{Name: "codex developer", Role: model.RoleDeveloper, ModelProvider: "codex"})
	if err != nil {
		t.Fatal(err)
	}
	got, err := runtime.process05CodexAgent(ctx, execution.TaskExecution{TaskID: "task", AssignedRole: string(model.RoleDeveloper)})
	if err != nil || got != first.ID {
		t.Fatalf("unique eligible Codex agent = %q, %v; want %q", got, err, first.ID)
	}
	if _, err := runtime.RegisterAgent(ctx, RegisterAgentRequest{Name: "second codex developer", Role: model.RoleDeveloper, ModelProvider: "codex"}); err != nil {
		t.Fatal(err)
	}
	if _, err := runtime.process05CodexAgent(ctx, execution.TaskExecution{TaskID: "task", AssignedRole: string(model.RoleDeveloper)}); !errors.Is(err, model.ErrInvalid) {
		t.Fatalf("ambiguous Codex worker selection must fail closed: %v", err)
	}
}

func TestProcess05PlanRunUsesDurableCanonicalTaskForCodex(t *testing.T) {
	ctx := context.Background()
	repo := runtimeRepo(t)
	if _, err := Bootstrap(ctx, repo.Path()); err != nil {
		t.Fatal(err)
	}
	fake := newFakeCodexAdapter()
	runtime, err := OpenWithOptions(ctx, repo.Path(), Options{Adapters: map[string]adapter.Adapter{"codex": fake}})
	if err != nil {
		t.Fatal(err)
	}
	defer runtime.Close()
	goal := planGoal()
	goal.SuccessCriteria = []string{"output exists"}
	if err := runtime.Store().SaveGoalContract(ctx, goal, 0); err != nil {
		t.Fatal(err)
	}
	now := time.Now().UTC()
	capacity := goalintake.UnknownCapacity("codex", true)
	_, err = runtime.Plans().Create(ctx, CreatePlanRequest{
		SessionID: goal.SessionID, ProjectID: runtimePlanProject,
		Tasks:             []plan.Task{{ID: "plan-local-task", Title: "write Codex output", Mutating: true, Paths: []string{"codex_output.txt"}, Criteria: []string{"output exists"}}},
		Candidates:        []goalintake.Candidate{{Provider: "codex", Model: "gpt-5.6-terra", Capacity: capacity, Governance: constitution.GovernanceVerified}},
		HarnessCandidates: []plan.HarnessCandidate{{Profile: model.HarnessProfile{Harness: "codex", InstalledVersion: "0.154.0", SupportedModels: []string{"gpt-5.6-terra"}, DefaultModel: "gpt-5.6-terra", ProbeEvidenceID: "EV-codex", ProbedAt: now}, InstalledVersion: "0.154.0", Provider: "codex", Capacity: capacity}},
	})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := runtime.Plans().Approve(ctx, runtimePlanProject); err != nil {
		t.Fatal(err)
	}
	if _, err := runtime.RegisterAgent(ctx, RegisterAgentRequest{Name: "planned codex", Role: model.RoleDeveloper, ModelProvider: "codex"}); err != nil {
		t.Fatal(err)
	}
	run, err := runtime.Execution().StartRun(ctx, goal.SessionID, runtimePlanProject)
	if err != nil {
		t.Fatal(err)
	}
	executed, err := runtime.Execution().ExecuteRun(ctx, run.RunID)
	if err != nil {
		t.Fatal(err)
	}
	if executed.State == execution.RunNeedsApproval {
		var approvalID string
		for _, task := range executed.Tasks {
			approvalID = task.ApprovalID
		}
		if approvalID == "" {
			t.Fatal("Process 05 requested approval without an exact record")
		}
		if err := runtime.Execution().Approve(ctx, approvalID, "operator", "reviewed"); err != nil {
			t.Fatal(err)
		}
		executed, err = runtime.Execution().ExecuteRun(ctx, run.RunID)
	}
	if fake.runs != 1 || !strings.HasPrefix(fake.lastReq.TaskID, "TASK-P05-") {
		t.Fatalf("Process 05 did not invoke Codex with its durable canonical task: err=%v state=%s tasks=%#v runs=%d request=%#v", err, executed.State, executed.Tasks, fake.runs, fake.lastReq)
	}
}

// TestProcess05CodexAppServerLiveApprovalE2E is deliberately opt-in: it uses
// the operator's installed Codex account and creates an isolated temporary
// repository. Unlike the adapter smoke test, it proves the canonical Process
// 04 handoff, Process 05 run, exact native approval, same-turn continuation,
// durable evidence, and Process 06 handoff path together.
func TestProcess05CodexAppServerLiveApprovalE2E(t *testing.T) {
	if os.Getenv("MARSHAL_CODEX_APP_SERVER_P05_E2E") != "1" {
		t.Skip("set MARSHAL_CODEX_APP_SERVER_P05_E2E=1 to run real governed Codex app-server Process 05 E2E")
	}
	if os.Getenv("MARSHAL_CODEX_APP_SERVER_ALLOW_HOST_CONFIG") != "1" {
		t.Skip("real local app-server E2E currently requires the explicit temporary host-config override")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()
	repo := runtimeRepo(t)
	if _, err := Bootstrap(ctx, repo.Path()); err != nil {
		t.Fatal(err)
	}
	runtime, err := Open(ctx, repo.Path())
	if err != nil {
		t.Fatal(err)
	}
	defer runtime.Close()
	goal := planGoal()
	goal.SuccessCriteria = []string{"marker file exists"}
	goal.DesiredOutcome = "A governed marker file exists in the isolated task worktree."
	if err := runtime.Store().SaveGoalContract(ctx, goal, 0); err != nil {
		t.Fatal(err)
	}
	now := time.Now().UTC()
	capacity := goalintake.UnknownCapacity("codex", true)
	_, err = runtime.Plans().Create(ctx, CreatePlanRequest{
		SessionID: goal.SessionID, ProjectID: runtimePlanProject,
		Tasks: []plan.Task{{
			ID: "live-app-server-task", Mutating: true, Paths: []string{"marshal_appserver_e2e_marker.txt"}, Criteria: []string{"marker file exists"},
			Title: "Use the normal Codex tool workflow to create marshal_appserver_e2e_marker.txt containing exactly MARSHAL_APP_SERVER_E2E. Do not modify any other file.",
		}},
		Candidates:        []goalintake.Candidate{{Provider: "codex", Model: "gpt-5.6-terra", Capacity: capacity, Governance: constitution.GovernanceVerified}},
		HarnessCandidates: []plan.HarnessCandidate{{Profile: model.HarnessProfile{Harness: "codex", InstalledVersion: "live", SupportedModels: []string{"gpt-5.6-terra"}, DefaultModel: "gpt-5.6-terra", ProbeEvidenceID: "EVID-live-codex", ProbedAt: now}, InstalledVersion: "live", Provider: "codex", Capacity: capacity}},
	})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := runtime.Plans().Approve(ctx, runtimePlanProject); err != nil {
		t.Fatal(err)
	}
	if _, err := runtime.RegisterAgent(ctx, RegisterAgentRequest{Name: "live governed codex", Role: model.RoleDeveloper, ModelProvider: "codex"}); err != nil {
		t.Fatal(err)
	}
	run, err := runtime.Execution().StartRun(ctx, goal.SessionID, runtimePlanProject)
	if err != nil {
		t.Fatal(err)
	}
	paused, err := runtime.Execution().ExecuteRun(ctx, run.RunID)
	if err != nil {
		t.Fatal(err)
	}
	// The Process 04 mutating-task approval is a separate canonical gate. It
	// must be decided before the provider is launched; never mistake it for a
	// native app-server tool approval or bypass it to make this E2E shorter.
	for _, task := range paused.Tasks {
		if task.State == execution.TaskNeedsApproval && task.NativeTurn == nil && task.ApprovalID != "" {
			if err := runtime.Execution().Approve(ctx, task.ApprovalID, "live-e2e-operator", "approved Process 04 task gate"); err != nil {
				t.Fatal(err)
			}
			paused, err = runtime.Execution().ExecuteRun(ctx, run.RunID)
			if err != nil {
				t.Fatal(err)
			}
			break
		}
	}
	deadline := time.Now().Add(90 * time.Second)
	decidedNativeApprovals := make(map[string]struct{})
	var completed execution.ExecutionRun
	for time.Now().Before(deadline) {
		completed, err = runtime.Execution().GetRun(ctx, run.RunID)
		if err != nil {
			t.Fatal(err)
		}
		if completed.State == execution.RunDonePendingVerification || completed.State.IsTerminal() {
			break
		}
		if completed.State == execution.RunNeedsApproval {
			for _, task := range completed.Tasks {
				if task.State != execution.TaskNeedsApproval || task.ApprovalID == "" || task.NativeTurn == nil {
					continue
				}
				if task.NativeTurn.ThreadID == "" || task.NativeTurn.TurnID == "" || task.NativeTurn.ConstraintDigest == "" || task.NativeTurn.Worktree == "" {
					t.Fatalf("incomplete durable native binding: %#v", task.NativeTurn)
				}
				if _, decided := decidedNativeApprovals[task.ApprovalID]; decided {
					continue
				}
				// A native approval is policy-dependent and a single turn may
				// request more than one exact action. Each decision below enters
				// the canonical approval manager and is bounded so a changed model
				// behavior cannot silently gain unbounded approvals in this E2E.
				if len(decidedNativeApprovals) >= 12 {
					t.Fatalf("native turn requested more than twelve independently reviewed approvals")
				}
				approvalCtx, approvalCancel := context.WithTimeout(ctx, 20*time.Second)
				err := runtime.Execution().Approve(approvalCtx, task.ApprovalID, "live-e2e-operator", "reviewed exact native request")
				approvalCancel()
				if err != nil {
					t.Fatal(err)
				}
				decidedNativeApprovals[task.ApprovalID] = struct{}{}
			}
		}
		time.Sleep(250 * time.Millisecond)
	}
	if completed.State != execution.RunDonePendingVerification {
		taskStates := make(map[string]string, len(completed.Tasks))
		for id, task := range completed.Tasks {
			taskStates[id] = fmt.Sprintf("state=%s native=%t approval=%t", task.State, task.NativeTurn != nil, task.ApprovalID != "")
		}
		t.Fatalf("native approval continuation did not complete Process 05: state=%s phase=%s tasks=%v decided_native_approvals=%d failures=%#v", completed.State, completed.CurrentPhase, taskStates, len(decidedNativeApprovals), completed.Failures)
	}
	if len(completed.Evidence) == 0 {
		t.Fatal("completed native turn produced no Process 05 evidence")
	}
	completedTask, ok := completed.Tasks["live-app-server-task"]
	if !ok || completedTask.WorktreePath == "" {
		t.Fatalf("completed native task has no canonical worktree binding: %#v", completed.Tasks)
	}
	// Process 05 deliberately executes in a task worktree. Reading the parent
	// repository here would test an unstated merge operation rather than the
	// exact isolated workspace that the native turn and its evidence bind.
	marker, err := os.ReadFile(filepath.Join(completedTask.WorktreePath, "marshal_appserver_e2e_marker.txt"))
	if err != nil || string(marker) != "MARSHAL_APP_SERVER_E2E" {
		t.Fatalf("real Codex turn did not produce the independently readable bounded output: marker=%q err=%v task=%#v evidence=%#v", marker, err, completedTask, runtime.Execution().Engine().EvidenceOracle().ListEvidenceForRun(run.RunID))
	}
	bundle, err := runtime.Execution().AssembleHandoffBundle(ctx, run.RunID)
	if err != nil || bundle.RunID != run.RunID || len(bundle.EvidenceBundle) == 0 {
		t.Fatalf("Process 06 handoff lacks native evidence: bundle=%#v err=%v", bundle, err)
	}
	// Process 06 receives its binding from the durable Process 05 run, then
	// evaluates a fresh, independently-read marker observation.  The provider
	// terminal event above is not treated as self-verifying evidence.
	binding, err := runtime.Verification().BindingForRun(ctx, run.RunID)
	if err != nil {
		t.Fatal(err)
	}
	verifiedAt := time.Now().UTC()
	verificationSession := verification.Session{
		ID:      "verify-live-codex-" + run.RunID,
		Version: 1,
		Binding: binding,
		Criteria: []verification.Criterion{{
			ID: "marker-created", Mandatory: true, ClaimIDs: []string{"marker-readback"},
		}},
		Claims: []verification.Claim{{
			ID: "marker-readback", CriterionID: "marker-created", SemanticScope: []string{"marshal_appserver_e2e_marker.txt"}, EvidenceIDs: []string{"independent-marker-readback"},
		}},
		Evidence: []verification.Evidence{{
			ID: "independent-marker-readback", ClaimID: "marker-readback", Status: verification.StatusPass, ContentDigest: "marker:" + string(marker), TreeDigest: binding.TreeDigest, EnvironmentDigest: binding.EnvironmentDigest, ClusterID: "independent-local-readback", Attempts: 1, Passes: 1,
		}},
		RequiredChecks: map[string]verification.Status{"independent-marker-readback": verification.StatusPass}, CreatedAt: verifiedAt, UpdatedAt: verifiedAt,
	}
	if _, err := runtime.Verification().Start(ctx, verificationSession); err != nil {
		t.Fatal(err)
	}
	verified, err := runtime.Verification().Evaluate(ctx, verificationSession.ID)
	if err != nil || verified.State != verification.VerifiedComplete {
		t.Fatalf("Process 06 verification=%+v err=%v", verified, err)
	}
}

func TestCodexModelPreferenceIsValidatedDurableAndCASBound(t *testing.T) {
	ctx := context.Background()
	repo := runtimeRepo(t)
	if _, err := Bootstrap(ctx, repo.Path()); err != nil {
		t.Fatal(err)
	}

	fake := newFakeCodexAdapter()
	runtime, err := OpenWithOptions(ctx, repo.Path(), Options{Adapters: map[string]adapter.Adapter{"codex": fake}})
	if err != nil {
		t.Fatal(err)
	}

	created, err := runtime.SetCodexModelPreference(ctx, "gpt-6-astra", 0)
	if err != nil {
		t.Fatalf("set Codex preference: %v", err)
	}
	if created.Revision != 1 || created.Model != "gpt-6-astra" {
		t.Fatalf("created preference = %+v", created)
	}
	if _, err := runtime.SetCodexModelPreference(ctx, "gpt-fake-nonexistent", created.Revision); !errors.Is(err, model.ErrInvalid) {
		t.Fatalf("unknown model preference error = %v, want ErrInvalid", err)
	}
	if _, err := runtime.SetCodexModelPreference(ctx, "gpt-5.6-terra", 0); !errors.Is(err, model.ErrConflict) {
		t.Fatalf("stale preference write error = %v, want ErrConflict", err)
	}
	if err := runtime.Close(); err != nil {
		t.Fatal(err)
	}

	restarted, err := OpenWithOptions(ctx, repo.Path(), Options{Adapters: map[string]adapter.Adapter{"codex": newFakeCodexAdapter()}})
	if err != nil {
		t.Fatal(err)
	}
	defer restarted.Close()
	recovered, err := restarted.CodexModelPreference(ctx)
	if err != nil {
		t.Fatalf("read preference after restart: %v", err)
	}
	if recovered != created {
		t.Fatalf("recovered preference = %+v, want %+v", recovered, created)
	}
}

func TestRuntimeProjectCodexSkillInstallIsDigestBoundAndAudited(t *testing.T) {
	ctx := context.Background()
	repo := runtimeRepo(t)
	if _, err := Bootstrap(ctx, repo.Path()); err != nil {
		t.Fatal(err)
	}
	source := filepath.Join(repo.Path(), ".agents", "skills", "project-skill")
	if err := os.MkdirAll(source, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(source, "SKILL.md"), []byte("---\nname: project-skill\n---\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	runtime, err := Open(ctx, repo.Path())
	if err != nil {
		t.Fatal(err)
	}
	defer runtime.Close()
	digest, err := codex.PreviewProjectSkill(repo.Path(), "project-skill")
	if err != nil {
		t.Fatal(err)
	}
	t.Setenv("CODEX_HOME", t.TempDir())
	got, err := runtime.InstallProjectCodexSkill(ctx, "project-skill", digest)
	if err != nil || got != digest {
		t.Fatalf("install = %q, %v", got, err)
	}
	events, err := runtime.Events(ctx)
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, event := range events {
		if event.Type == "CODEX_PROJECT_SKILL_INSTALLED" && event.Data["digest"] == digest {
			found = true
		}
	}
	if !found {
		t.Fatal("skill install audit event missing")
	}
}

func TestRuntimeProjectCodexSkillInstallCompensatesAuditFailure(t *testing.T) {
	ctx := context.Background()
	repo := runtimeRepo(t)
	if _, err := Bootstrap(ctx, repo.Path()); err != nil {
		t.Fatal(err)
	}
	source := filepath.Join(repo.Path(), ".agents", "skills", "audit-compensation")
	if err := os.MkdirAll(source, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(source, "SKILL.md"), []byte("---\nname: audit-compensation\n---\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	runtime, err := Open(ctx, repo.Path())
	if err != nil {
		t.Fatal(err)
	}
	digest, err := codex.PreviewProjectSkill(repo.Path(), "audit-compensation")
	if err != nil {
		t.Fatal(err)
	}
	codexHome := t.TempDir()
	t.Setenv("CODEX_HOME", codexHome)
	// Closing the store makes the durable audit append fail after the adapter
	// has copied its private snapshot. The runtime must compensate that copy.
	if err := runtime.Close(); err != nil {
		t.Fatal(err)
	}
	if _, err := runtime.InstallProjectCodexSkill(ctx, "audit-compensation", digest); err == nil {
		t.Fatal("install succeeded despite unavailable audit store")
	}
	if _, err := os.Stat(filepath.Join(codexHome, "skills", "audit-compensation")); !os.IsNotExist(err) {
		t.Fatalf("unaudited skill was left installed: %v", err)
	}
}

func TestCodexRunEvidenceAndSessionBinding(t *testing.T) {
	ctx := context.Background()
	repo := runtimeRepo(t)
	if _, err := Bootstrap(ctx, repo.Path()); err != nil {
		t.Fatal(err)
	}

	fake := newFakeCodexAdapter()
	runtime, err := OpenWithOptions(ctx, repo.Path(), Options{
		Adapters: map[string]adapter.Adapter{"codex": fake},
	})
	if err != nil {
		t.Fatal(err)
	}
	defer runtime.Close()

	agent, err := runtime.RegisterAgent(ctx, RegisterAgentRequest{Name: "dev-codex-exec", Role: model.RoleDeveloper, ModelProvider: "codex"})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := runtime.ImportTasks(ctx, []model.Task{
		{ID: "TASK-CODEX-RUN", Title: "governed codex run", Status: model.TaskReady, Risk: model.R1},
	}); err != nil {
		t.Fatal(err)
	}

	// Run with explicit model
	res, err := runtime.Run(ctx, RunRequest{
		TaskID:           "TASK-CODEX-RUN",
		AgentID:          agent.ID,
		Adapter:          "codex",
		Model:            "gpt-5.6-terra",
		ExpectedRevision: 0,
	})
	if err != nil {
		t.Fatalf("Runtime.Run failed: %v", err)
	}

	if res.Status != "success" {
		t.Fatalf("res.Status = %s, want success", res.Status)
	}
	if res.SessionID != "thread_codex_governed_123" {
		t.Errorf("res.SessionID = %q, want thread_codex_governed_123", res.SessionID)
	}
	if res.Model != "gpt-5.6-terra" {
		t.Errorf("res.Model = %q, want gpt-5.6-terra", res.Model)
	}
	if res.RequestedModel != "gpt-5.6-terra" {
		t.Errorf("res.RequestedModel = %q, want gpt-5.6-terra", res.RequestedModel)
	}

	// Verify evidence nodes contain model and session_id
	cmdEv, err := runtime.Evidence(ctx, evidence.NodeID("EVIDENCE-RUN-"+res.RunID+"-COMMAND"))
	if err != nil {
		t.Fatalf("failed to retrieve COMMAND evidence: %v", err)
	}
	if cmdEv.Metadata["requested_model"] != "gpt-5.6-terra" {
		t.Errorf("cmd evidence requested_model = %q, want gpt-5.6-terra", cmdEv.Metadata["requested_model"])
	}
	if cmdEv.Metadata["effective_model"] != "gpt-5.6-terra" {
		t.Errorf("cmd evidence effective_model = %q, want gpt-5.6-terra", cmdEv.Metadata["effective_model"])
	}
	if cmdEv.Metadata["session_id"] != "thread_codex_governed_123" {
		t.Errorf("cmd evidence session_id = %q, want thread_codex_governed_123", cmdEv.Metadata["session_id"])
	}

	outEv, err := runtime.Evidence(ctx, evidence.NodeID("EVIDENCE-RUN-"+res.RunID+"-OUTPUT"))
	if err != nil {
		t.Fatalf("failed to retrieve OUTPUT evidence: %v", err)
	}
	if outEv.Metadata["effective_model"] != "gpt-5.6-terra" {
		t.Errorf("out evidence effective_model = %q, want gpt-5.6-terra", outEv.Metadata["effective_model"])
	}
	if outEv.Metadata["session_id"] != "thread_codex_governed_123" {
		t.Errorf("out evidence session_id = %q, want thread_codex_governed_123", outEv.Metadata["session_id"])
	}

	envEv, err := runtime.Evidence(ctx, evidence.NodeID("EVIDENCE-RUN-"+res.RunID+"-ENV"))
	if err != nil {
		t.Fatalf("failed to retrieve ENV evidence: %v", err)
	}
	if envEv.Metadata["effective_model"] != "gpt-5.6-terra" {
		t.Errorf("env evidence effective_model = %q, want gpt-5.6-terra", envEv.Metadata["effective_model"])
	}
	if envEv.Metadata["session_id"] != "thread_codex_governed_123" {
		t.Errorf("env evidence session_id = %q, want thread_codex_governed_123", envEv.Metadata["session_id"])
	}

	// 3. Duplicate submit rejection: running again with stale revision 0 must fail
	_, err = runtime.Run(ctx, RunRequest{
		TaskID:           "TASK-CODEX-RUN",
		AgentID:          agent.ID,
		Adapter:          "codex",
		Model:            "gpt-5.6-terra",
		ExpectedRevision: 0,
	})
	if err == nil {
		t.Fatal("expected duplicate submit with stale revision to fail, got nil")
	}
}
