package app

import (
	"context"
	"database/sql"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/Zen1th53/marshal/internal/memory/importer"
)

func isolateSessionHistory(t *testing.T) {
	t.Helper()
	for _, env := range []string{"HOME", "XDG_CONFIG_HOME", "XDG_DATA_HOME", "CODEX_HOME", "CLAUDE_CONFIG_DIR", "PATH"} {
		t.Setenv(env, t.TempDir())
	}
	t.Setenv("MARSHAL_CLOUD_ENDPOINT", "off")
	for _, name := range []string{"codex", "claude", "opencode", "agy"} {
		if err := os.WriteFile(filepath.Join(os.Getenv("PATH"), name), []byte("#!/bin/sh\nexit 127\n"), 0700); err != nil {
			t.Fatal(err)
		}
	}
}
func importInventoryConversation(t *testing.T, r *Runtime, provider, id string, stamp time.Time) {
	t.Helper()
	data, err := json.Marshal(importer.SessionTranscript{SessionID: id, Provider: provider, Messages: []importer.Message{{Role: "user", Content: "visible inventory fixture", Timestamp: stamp}}})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := r.Memory().ImportSessionTranscript(context.Background(), testPrincipal("inventory-owner"), r.ProjectID(), data, false); err != nil {
		t.Fatal(err)
	}
}

func TestSessionInventoryImportsAndNativeSelection(t *testing.T) {
	// Bootstrap needs git; isolate provider lookup only after creating runtimes.
	r, _ := openTestMemoryService(t)
	other, _ := openTestMemoryService(t)
	isolateSessionHistory(t)
	old := time.Now().UTC().Add(-time.Hour)
	importInventoryConversation(t, r, "codex", "source with spaces", old)
	importInventoryConversation(t, r, "codex", "new-native", old.Add(time.Minute))
	importInventoryConversation(t, r, "claude", "claude-native", old)
	importInventoryConversation(t, other, "codex", "foreign-native", old)
	inv, err := r.Sessions(context.Background(), "")
	if err != nil {
		t.Fatal(err)
	}
	if len(inv.Native) != 3 {
		t.Fatalf("native=%+v", inv.Native)
	}
	for _, c := range inv.Native {
		if c.ProviderListed || c.Source != "transcript imported" {
			t.Fatalf("import claimed provider resumability: %+v", c)
		}
		if !strings.HasPrefix(c.ID, "native:"+c.Provider+":") {
			t.Fatalf("unqualified ID: %+v", c)
		}
	}
	selected, err := r.ResolveNativeConversation(context.Background(), "codex", "--last")
	if err != nil || selected.SourceID != "new-native" {
		t.Fatalf("latest=%+v err=%v", selected, err)
	}
	selected, err = r.ResolveNativeConversation(context.Background(), "codex", NativeConversationID("codex", r.ProjectRoot(), "source with spaces"))
	if err != nil || selected.SourceID != "source with spaces" {
		t.Fatalf("source ID lost: %+v %v", selected, err)
	}
	for _, tc := range []struct{ target, reason string }{
		{NativeConversationID("claude", r.ProjectRoot(), "claude-native"), "another provider"},
		{"claude-native", "another provider"},
		{NativeConversationID("codex", other.ProjectRoot(), "foreign-native"), "another project"},
		{"foreign-native", "unknown native conversation"},
		{"invented-native", "unknown native conversation"},
	} {
		if _, err := r.ResolveNativeConversation(context.Background(), "codex", tc.target); err == nil || !strings.Contains(err.Error(), tc.reason) {
			t.Fatalf("%s: %v", tc.target, err)
		}
	}
}

func TestSessionInventoryProviderHistoryOwnership(t *testing.T) {
	r, _ := openTestMemoryService(t)
	isolateSessionHistory(t)
	home := os.Getenv("CODEX_HOME")
	if err := os.MkdirAll(filepath.Join(home, "sessions"), 0700); err != nil {
		t.Fatal(err)
	}
	for _, tc := range []struct{ id, cwd string }{{"local-index", r.ProjectRoot()}, {"foreign-index", t.TempDir()}} {
		meta := map[string]any{"type": "session_meta", "payload": map[string]string{"id": tc.id, "cwd": tc.cwd}}
		data, _ := json.Marshal(meta)
		if err := os.WriteFile(filepath.Join(home, "sessions", tc.id+".jsonl"), append(data, '\n'), 0600); err != nil {
			t.Fatal(err)
		}
	}
	inv, err := r.Sessions(context.Background(), "codex")
	if err != nil || len(inv.Native) != 1 || inv.Native[0].SourceID != "local-index" || inv.Native[0].ProviderListed {
		t.Fatalf("history=%+v %v", inv, err)
	}
}

func TestSessionInventoryProviderListingVerifiesPresence(t *testing.T) {
	r, _ := openTestMemoryService(t)
	isolateSessionHistory(t)
	importInventoryConversation(t, r, "opencode", "listed", time.Now().UTC())
	data, _ := json.Marshal([]map[string]any{{"id": "listed", "directory": r.ProjectRoot(), "updated": time.Now().UnixMilli()}, {"id": "foreign", "directory": t.TempDir(), "updated": time.Now().UnixMilli() + 1000}})
	// Shell literal data contains paths generated by TempDir only.
	script := "#!/bin/sh\nprintf '%s\\n' '" + string(data) + "'\n"
	if err := os.WriteFile(filepath.Join(os.Getenv("PATH"), "opencode"), []byte(script), 0700); err != nil {
		t.Fatal(err)
	}
	inv, err := r.Sessions(context.Background(), "opencode")
	if err != nil || len(inv.Native) != 1 || !inv.Native[0].ProviderListed || !strings.Contains(inv.Native[0].Source, "transcript imported") || !strings.Contains(inv.Native[0].Source, "provider listing") {
		t.Fatalf("listing=%+v %v", inv, err)
	}
}

func TestSessionInventoryPrivateDatabaseOwnership(t *testing.T) {
	r, _ := openTestMemoryService(t)
	isolateSessionHistory(t)
	ctx := context.Background()
	for _, provider := range []string{"opencode", "antigravity"} {
		t.Run(provider, func(t *testing.T) {
			var path string
			if provider == "opencode" {
				path = filepath.Join(t.TempDir(), "opencode.db")
				t.Setenv("MARSHAL_OPENCODE_DB", path)
			} else {
				base := filepath.Join(os.Getenv("HOME"), ".gemini", "antigravity-cli")
				if err := os.MkdirAll(filepath.Join(base, "conversations"), 0700); err != nil {
					t.Fatal(err)
				}
				path = filepath.Join(base, "conversation_summaries.db")
				for _, id := range []string{"local-private", "foreign-private"} {
					if err := os.WriteFile(filepath.Join(base, "conversations", id+".db"), nil, 0600); err != nil {
						t.Fatal(err)
					}
				}
			}
			db, err := sql.Open("sqlite", path)
			if err != nil {
				t.Fatal(err)
			}
			if provider == "opencode" {
				if _, err := db.Exec(`CREATE TABLE session (id TEXT, directory TEXT, time_updated INTEGER)`); err != nil {
					t.Fatal(err)
				}
				for _, tc := range []struct{ id, dir string }{{"local-private", r.ProjectRoot()}, {"foreign-private", t.TempDir()}} {
					if _, err := db.Exec(`INSERT INTO session VALUES (?,?,?)`, tc.id, tc.dir, time.Now().UnixMilli()); err != nil {
						t.Fatal(err)
					}
				}
			} else {
				if _, err := db.Exec(`CREATE TABLE conversation_summaries (conversation_id TEXT, workspace_uris TEXT)`); err != nil {
					t.Fatal(err)
				}
				for _, tc := range []struct{ id, dir string }{{"local-private", r.ProjectRoot()}, {"foreign-private", t.TempDir()}} {
					raw, _ := json.Marshal([]string{"file://" + tc.dir})
					if _, err := db.Exec(`INSERT INTO conversation_summaries VALUES (?,?)`, tc.id, string(raw)); err != nil {
						t.Fatal(err)
					}
				}
			}
			if err := db.Close(); err != nil {
				t.Fatal(err)
			}
			inv, err := r.Sessions(ctx, provider)
			if err != nil || len(inv.Native) != 1 || inv.Native[0].SourceID != "local-private" || inv.Native[0].ProviderListed {
				t.Fatalf("private history: %+v %v", inv, err)
			}
		})
	}
}

func TestSessionInventoryUnsafeHistoryMetadataOmitted(t *testing.T) {
	r, _ := openTestMemoryService(t)
	isolateSessionHistory(t)
	dir := filepath.Join(os.Getenv("CODEX_HOME"), "sessions")
	if err := os.MkdirAll(dir, 0700); err != nil {
		t.Fatal(err)
	}
	data, _ := json.Marshal(map[string]any{"type": "session_meta", "payload": map[string]string{"id": "AKIAIOSFODNN7EXAMPLE", "cwd": r.ProjectRoot()}})
	if err := os.WriteFile(filepath.Join(dir, "unsafe.jsonl"), append(data, '\n'), 0600); err != nil {
		t.Fatal(err)
	}
	inv, err := r.Sessions(context.Background(), "codex")
	if err != nil || len(inv.Native) != 0 || len(inv.Warnings) != 1 || strings.Contains(strings.Join(inv.Warnings, " "), "AKIA") {
		t.Fatalf("unsafe metadata: %+v %v", inv, err)
	}
}

func TestSessionInventoryBatchUsesNativeHomeAndProject(t *testing.T) {
	r, _ := openTestMemoryService(t)
	isolateSessionHistory(t)
	importInventoryConversation(t, r, "codex", "batch-source", time.Now().UTC())
	script := `#!/bin/sh
if [ "$1" = '--version' ]; then printf 'codex-cli 0.159.2\n'; exit 0; fi
printf 'HOME:<%s>\nDIR:<%s>\n' "$CODEX_HOME" "$PWD"
for arg do printf 'ARG:<%s>\n' "$arg"; done
`
	if err := os.WriteFile(filepath.Join(os.Getenv("PATH"), "codex"), []byte(script), 0700); err != nil {
		t.Fatal(err)
	}
	out, err := r.ExecuteNativeCodexConversation(context.Background(), "resume", "--last", []string{"quoted prompt"})
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"HOME:<" + os.Getenv("CODEX_HOME") + ">", "DIR:<" + r.ProjectRoot() + ">", "ARG:<exec>", "ARG:<resume>", "ARG:<batch-source>", "ARG:<quoted prompt>"} {
		if !strings.Contains(out, want) {
			t.Fatalf("missing %s: %s", want, out)
		}
	}
	if _, err := r.ExecuteNativeCodexConversation(context.Background(), "resume", NativeConversationID("codex", t.TempDir(), "batch-source"), nil); err == nil || !strings.Contains(err.Error(), "another project") {
		t.Fatalf("batch project: %v", err)
	}
	if _, err := r.ExecuteNativeCodexConversation(context.Background(), "fork", "--last", nil); err == nil || !strings.Contains(err.Error(), "terminal-only") {
		t.Fatalf("batch dialect: %v", err)
	}
}
